// <auto-generated />
using System;
using AMVACChemical.Entities.TrackAbout;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AMVACChemical.Migrations
{
    [DbContext(typeof(AMVAC_TrackaboutContext))]
    partial class AMVAC_TrackaboutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AMVACChemical.Entities.TrackAbout.Assets.Login", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.Property<bool>("Status");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("login");
                });
#pragma warning restore 612, 618
        }
    }
}
